name: Publish Docker image

on:
  push:
    branches: ["main"]
  workflow_dispatch:

jobs:
  build-and-push-keycloak-image:
    uses: MAD-Goat-Project/github-actions-workflows/.github/workflows/publish-docker.yml@main
    with:
      dockerfile_context: "keycloak"
      image_name: "mad-keycloak-service"
